name: Publish on merge to main

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: softwaremill/fablo

jobs:
  publish-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_LOGIN }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          shellcheck --version
          yamllint -v
          npm install
          ./fablo-build.sh --push
